let names = [
    "Kyoukai no Kanata",
    "Zankyo Sanka",
    "Kaikai Kitan",
    "Super * Affection",
    "Honey Come!!",
    "One In A Billion",
    "Yakusoku -Promise code-",
    "Last Chapter",
    "STONE OCEAN",
    "Say Goodbye",
    "Gyakkyou Spectrum",
    "Tomadoi Recipe",
    "Delta Decision",
    "I'm so excited (feat. Bobby John)",
    "Yuke",
    "Cynthia no Hikari",
    "Flamewall",
    "AVENGE WORLD",
    "Heavy Rotation",
    "Sing My Pleasure",
    "Koko kara Saki wa Uta ni Naranai",
    "START!! True dreams",
    "Like Flames",
    "reiwa anthem",
    "Plastic Smile",
    "Kira Kira Days",
    "The Big Black",
    "I Wanna Guinea Pig For Christmas",
    "Zutto Summer de Koishiteru",
    "Acacia",
    "CLOSER",
    "over and over",
    "FLAME",
    "Shiny Smily Story",
    "Nanairo Symphony",
    "FLYING OUT TO THE SKY",
    "Realize",
    "Songs Compilation IV",
    "Starlight Wonder",
    "Triple Baka",
    "sabotage",
    "Make you happy",
    "Beginner's Sailing",
    "Theater of Life",
    "Angel With A Shotgun",
    "Scar/let",
    "ChuChu Lovely MuniMuni MuraMura PrinPrin Boron Nururu ReroRero",
    "HAPPY PARTY TRAIN",
    "ANIMA",
    "1,000,000 TIMES",
    "crossing field",
    "Till the End",
    "courage",
    "IGNITE",
    "INNOCENCE",
    "Realize",
    "The Guinea Pig Is In Your Mind",
    "Wonder Stella",
    "Shuriken School",
    "Dori Dori",
    "Bubble Gun",
    "Megumi no Ame (TV Size)",
    "Songs Compilation III",
    "Hoshi o Atsumete",
    "Gurenge feat. Un3h [ dj-Jo Remix ]",
    "Anemone no Hana",
    "DROPOUT!?",
    "Sunflower",
    "Kyuukyoku Unbalance!",
    "Play the world",
    "Yasashisa no Riyuu",
    "starlog",
    "Cold Green Eyes feat. Roos Denayer",
    "Road of Resistance",
    "Dance with Minotaurus",
    "PADORU / PADORU",
    "Mitaiken HORIZON",
    "Yuuki wa Doko ni? Kimi no Mune ni!",
    "where you are",
    "Koukai no Uta",
    "Resolution",
    "Berry Go!!",
    "HAPPY HAPPY",
    "Selfrontier",
    "identity",
    "Yosoku Fukano Driving!",
    "Guinea Pig Olympics",
    "Bouken Type A, B, C!!",
    "Ima Suki ni Naru.",
    "AaAaAaAAaAaAAa",
    "WINGS OF JUSTICE",
    "Brightest Melody",
    "Natsuzora Yell",
    "Louder than steel",
    "osu!memories 2",
    "Til Death",
    "Team Magma & Aqua Leader Battle Theme (Unofficial)",
    "Guinea Pig Bridge",
    "Ao no Kanata",
    "Boku o Mitsukete",
    "Diamond",
    "MIIRO",
    "JUSTadICE",
    "American Girls",
    "narrative",
    "Watashi o Kureta Minna e",
    "Totsugeki Rock",
    "Rockefeller Street",
    "Ai no Sukima",
    "Scarlet Flower",
    "Kyouran Hey Kids!!",
    "Overkill",
    "Colorful",
    "Gold Dust",
    "United (L.A.O.S Remix)",
    "Ringo Ribbon",
    "Taisetsu no Tsukurikata (Asterisk Remix)",
    "Niji o Ametara",
    "U Got That",
    "Taisetsu no Tsukurikata",
    "Kimi to Iu Tokuiten",
    "POP/STARS",
    "Walk This Way!",
    "Idola no Circus",
    "A New Journey",
    "Guess Who Is Back",
    "Kaze no Uta",
    "Sorairo Picture",
    "RESISTER",
    "STORIES",
    "Reimei",
    "Fatima",
    "BLACK MEMORY",
    "quaver",
    "RAISE MY SWORD",
    "Reimei",
    "Snow Halation",
    "Tenshi ni Fureta yo!",
    "Kimi no Bouken",
    "Clock Strikes",
    "Heart Shaker",
    "1HOPE SNIPER",
    "The Noise of Rain",
    "color",
    "Storyteller",
    "Cry Thunder",
    "Echame La Culpa",
    "Kimi no Sei",
    "Sora ni Utaeba",
    "Unmei Dilemma",
    "Watashi, Idol Sengen",
    "Sword Art Online Compilation",
    "ADAMAS",
    "Natsuiro Egao de 1, 2, Jump!",
    "DANZEN! Futari wa PreCure Ver. MaxHeart",
    "Hoshikuzu no Interlude",
    "Super Driver",
    "Harumachi Clover",
    "km/h",
    "CHEER UP",
    "MY LIBERATION",
    "Songs Compilation II",
    "Black Rover",
    "Star!!",
    "MAYDAY",
    "Despacito",
    "Q&A Recital!",
    "o!IMC#2 Compilation",
    "ReI",
    "How Far I'll Go",
    "Leave It All To Me",
    "Do you realize?",
    "SLATEPORT CITY",
    "Sidetracked Day",
    "Monochrome Butterfly",
    "Make a Move",
    "FREEDOM DIVE",
    "Shounen Ripples",
    "Dead To Me",
    "(can you) understand me?",
    "Yugioh! Theme",
    "Kimi no Sumu Machi",
    "Los! Los! Los!",
    "Blade Dance",
    "Colors Power ni Omakasero!",
    "Natsu no Owari",
    "Best FriendS",
    "Airman ga Taosenai",
    "Orange",
    "Putin's Boner",
    "Platform Syndrome",
    "Tsuki to Hanatabe",
    "Songs Compilation",
    "Passcode 4854",
    "Hashi no Kakera",
    "Kimi no shiranai monogatari",
    "Toumei Elegy",
    "Immortal Flame"
]

export default names;